services:
  db:
    container_name: mysql-das
    image: mysql:8.0
    restart: always
    ports:
      - "54545:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testing123
      MYSQL_DATABASE: bpitdas
    volumes:
      - bpitdas:/var/lib/mysql
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 20s
      retries: 10
      start_period: 60s
      timeout: 60s

  bpit-das-frontend-v2:
    container_name: bpit-das-frontend-v2
    image: bpit-das-frontend-v2:latest
    restart: always
    environment:
      TZ: Asia/Hong_Kong
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50000:50000"

volumes:
  bpitdas: